name = "QuanEstimation"
uuid = "088c8dff-a786-4a66-974c-03d3f6773f87"
authors = ["Jing Liu <liujingphys@hust.edu.cn>", "Huaiming Yu <Huaimingyuuu@gmail.com>", "Mao Zhang <zhangmao2018@hust.edu.cn>"]
version = "0.2.0"

[deps]
QuanEstimationBase = "9769ca81-ed10-4016-bab9-e66dc61d4d60"

[weakdeps]

[extensions]

[compat]
QuanEstimationBase = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
